[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 4294967295
fs_permissions = [{ access = "read-write", path = "/tmp"}]
solc = "0.8.28"
evm_version = "paris"
remappings = [
  "account-abstraction/=lib/account-abstraction/contracts/"
]

[fuzz]
max_test_rejects = 1000000

[fmt]
# Explicitly define all formatting rules
multiline_func_header = "params_first"
single_line_statement_blocks = "multi"
sort_imports = true
contract_new_lines = true
override_spacing = false
line_length = 120
tab_width = 2
bracket_spacing = true
int_types = "long"
quote_style = "double"
hex_underscore = "remove"
wrap_comments = false
